"""add_teacher_login_accounts

Revision ID: 8c049fab2653
Revises: c60854c1980f
Create Date: 2026-04-27 14:55:08.230454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c049fab2653'
down_revision = 'c60854c1980f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_teacher_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_teacher_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher', schema=None) as batch_op:
        batch_op.drop_constraint('fk_teacher_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('uq_teacher_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
