"""professional_system_features

Revision ID: c60854c1980f
Revises: da69578ae518
Create Date: 2026-04-27 02:18:24.965843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60854c1980f'
down_revision = 'da69578ae518'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.String(length=20), nullable=False),
    sa.Column('end_time', sa.String(length=20), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_rooms.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_class_rooms_teacher_id_teacher', 'teacher', ['teacher_id'], ['id'])

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('homework_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('midterm_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('final_score', sa.Float(), nullable=False, server_default='0'))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guardian_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('guardian_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('emergency_phone', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subject_teacher_id_teacher', 'teacher', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subject_teacher_id_teacher', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('photo_url')
        batch_op.drop_column('emergency_phone')
        batch_op.drop_column('guardian_phone')
        batch_op.drop_column('guardian_name')
        batch_op.drop_column('address')

    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('final_score')
        batch_op.drop_column('midterm_score')
        batch_op.drop_column('homework_score')
        batch_op.drop_column('quiz_score')

    with op.batch_alter_table('class_rooms', schema=None) as batch_op:
        batch_op.drop_constraint('fk_class_rooms_teacher_id_teacher', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    op.drop_table('schedule')
    op.drop_table('audit_log')
    op.drop_table('teacher')
    # ### end Alembic commands ###
